### ISSUE TITLE
browser-style.css 不支持农历

### ISSUE THREAD

**Issue by NateScarlet** [Hzy0913/mpvue-calendar#27]
![image](https://user-images.githubusercontent.com/21083014/54185467-0e9e5300-44e4-11e9-913c-4d195272613e.png)

不开农历正常 开农历就错位了
用 `mpvue-calendar/src/style.css` 也正常

**Comment by NateScarlet** [comment]
![image](https://user-images.githubusercontent.com/21083014/54185864-f975f400-44e4-11e9-89e7-85cfe9fb1145.png)

用这个好像这样能修复
```scss
  .mpvue-calendar {
    .lunarStyle {
      .mc-text {
        overflow: visible;
        bottom: 1em;
      }
    }
  }
```
